gallery_dl/extractor/imagehosts.py
Hello,
gallery-dl doesn't work correctly from some images on pixhost that is part of an album.
The original code will fetch the first image of the album instead of the image shown for that URL.
Try this URL for a test case:
http://pixhost.org/show/1304/36787835_img_20170114_110314.jpg
This patch fixes the above described problem.
Thank you.
=> Fixed the module for pixhost

gallery_dl/extractor/pixiv.py
Pixiv user links can include a tag (https://www.pixiv.net/member_illust.php?id={user}&tag={tag}), which means to only show images with that tag. This PR adds support for that to the extractor.
=> [pixiv] support tag for user downloads

gallery_dl/extractor/directlink.py
Add WebP, still not that common, but it's increasing.
Add 3rd JPEG variant (https://en.wikipedia.org/wiki/JPEG#JPEG_filename_extensions)
Never seen JFIF in the wild, would probably be overkill.
Extend Ogg formats (https://en.wikipedia.org/wiki/Ogg; https://wiki.xiph.org/MIME_Types_and_File_Extensions)
=> Update directlink.py with additional file exts.

gallery_dl/extractor/luscious.py, gallery_dl/util.py
this is little fix to error i met when parsing luscious
```
File "/home/q/.git/gallery-dl/gallery_dl/job.py", line 44, in run
for msg in self.extractor:
File "/home/q/.git/gallery-dl/gallery_dl/extractor/luscious.py", line 43, in items
data = self.get_job_metadata()
File "/home/q/.git/gallery-dl/gallery_dl/extractor/luscious.py", line 64, in get_job_metadata
data["lang"] = util.language_to_code(data["language"])
File "/home/q/.git/gallery-dl/gallery_dl/util.py", line 90, in language_to_code
lang = lang.capitalize()
AttributeError: 'NoneType' object has no attribute 'capitalize'
```
```
[luscious][error] An unexpected error occurred:
File "/home/q/.git/gallery-dl/gallery_dl/job.py", line 44, in run
for msg in …
```
=> chg: dev: fix error

gallery_dl/extractor/imgur.py
Add {title} keyword..
Images on Imgur don't necessarily have a title, but I think most of them do, and since this should not break anything else..
Not sure about the right order. Proposed is:
`"{category}_{hash}_{title}.{extension}"` 
Alternatively:
`"{category}_{title}_{hash}.{extension}"`
This would have the benefit of alphabetical sorting of images with similar titles, they are likely to be related, and now they would be in a proper order, at least to some extent.
Of course. feel free to modify, change, reject. etc..
=> Update imgur.py to include 'title' of single image

gallery_dl/extractor/idolcomplex.py, gallery_dl/extractor/sankaku.py
Hello, I modified `sankaku.py` and `idolcomplex.py`. It now supports multi-page URL like https://chan.sankakucomplex.com/?tags=marie_rose&page=98&next=3874906 **(NSFW)**.
Please review my code.
=> support multi-page URL

setup.py
I encountered the following error when installing `gallery-dl` using Python 3.5.2 on Ubuntu 16.04 LTS.
Installation command
```bash
python3 setup.py install
```
Encountered error
```text
File "setup.py", line 21, in <module>
exec(read("gallery_dl/version.py"))
File "setup.py", line 17, in read
return open(os.path.join(os.path.dirname(__file__), fname)).read()
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)
```
In the file `gallery_dl/version.py`, there is a non-ascii character in name `Mike Fährmann`. 
So `setup.py` failed to read the version with default encoding ascii and raised the …
=> Fix UnicodeDecodeError during installation

gallery_dl/extractor/tumblr.py
There seems to be another sub-domain for videos, apparently..
Not just
`vt(.media).tumblr`
`vtt(media).tumblr`
But also
`ve(.media).tumblr`
Two examples pulled via `\posts\` endpoint on Web API Console:
```
"video_url": "https://ve.media.tumblr.com/tumblr_n1zsb87J961ts7u0r.mp4",
"video_url": "https://ve.media.tumblr.com/tumblr_n1zsdjVyDf1ts7u0r.mp4",
```
Note that both return `403`, that old issue with videos on Tumblr etc. pp.
I think I've only seen one at `ve.media.tumblr.com` so far, but that was working.
So this exists 😄 
Please comment/change/edit as you see fit.
@mikf I've only tested these changes with the regex101.com tool (Python mode) and not via local Python interpreter or something, but I think this should work.
Also, a question just for understanding:
Do I get this right, …
=> [tumblr] update regex for video subdomain

gallery_dl/extractor/__init__.py, gallery_dl/extractor/instagram.py
The extractor scrapes `instagram.com/<user>' timelines and
`instagram.com/p/<shortcode>' by mimicking the behaviour of a web
browser and extracting the sharedData JSON of the single pages.
Please note that this mean that for user timelines we also do an
extra request to the `instagram.com/p/<shortcode>' page but this
permit to have consistent (and all) information about the media
fetched.
The MD5 logic used for X-Instagram-GIS was documented in
<https://stackoverflow.com/questions/49786980/>
The current known (and documented via TODO comment) limitation of
the extractor is that it treats `GraphSidecar' media (that contains
multiple images) like `GraphImage'.  So, for `GraphSidecar' media - at the
moment -only an image is retrieved, not all of them.
(I would prefer to add support for it …
=> Add support for instagram.com user profiles and pages

.gitignore, snap/local/launchers/gallery-dl-launch, snap/local/launchers/workaround-snap-arch-triplet-launch, snap/snapcraft.yaml
This patch implements the necessary details to package gallery-dl as a snap that can be run on a broad range of supporting GNU/Linux distributions[1].
[1] https://snapcraft.io/
=> Implement snap packaging, snaps are universal linux packages

snap/snapcraft.yaml
This patch re-implements the pull step that will only build development snapshots snaps if the latest tagged release has been promoted to the stable channel.  This ensures that there's always a revision of the stable release snap available in the edge channel for the publisher to promote to stable as currently the automated build infrastructure only supports build on code push (but not new tagged releases) at this time.
The mechanism is inspired from the snapcrafters adopted snaps workflow, documented in the following forum topic:
[The automatic build and pubish process of snaps owned by the Snapcrafters - doc - snapcraft.io](https://forum.snapcraft.io/t/autopublishing-of-snapcrafters-organizations-snaps-how/7954/2)
Refer the following forum topic for a possible solution proposal of this …
=> Implement selective pulling for building tagged release snaps

snap/local/launchers/gallery-dl-launch, snap/snapcraft.yaml
Refer-to: The personal-files interface - doc - snapcraft.io <https://forum.snapcraft.io/t/the-personal-files-interface/9357>
Refer-to: The system-files interface - doc - snapcraft.io <https://forum.snapcraft.io/t/the-system-files-interface/9358>
=> snap: Support official config paths via *-files confinement interfaces

snap/snapcraft.yaml
This patch adds a copy of the youtube-dl package to the snap to enable the video downloading feature.
Tested with the Twitter extractor.
=> snap: Support downloading video using youtube-dl

gallery_dl/extractor/instagram.py
Refactor _extract_postpage() to always return a list of medias.
Fetch common keywords and gracefully handle GraphSidecar media type
by extracting each single media and adding `sidecar_media_id' and
`sidecar_shortcode' keywords to indicate the parent of sidecar
childrens.
While here join the copyright comment lines in a single one.
Closes #178.
=> [instagram] Add support for GraphSidecar media types

gallery_dl/extractor/instagram.py
Add support for hashtags (TagPage-s), i.e. explore/tags/<tag> URLs.
This also introduce a get_metadata() method in order to append
possible further metadata per-(sub)extractor.
Refactor and generalize _extract_profilepage() to _extract_page()
in order to be reused by _extract_profilepage() and _extract_tagpage()
simply by passing the type of page (`ProfilePage' or `TagPage') and picking up
the respective fields in shared data.
=> [instagram] Add support for hashtags (InstagramTagExtractor)

snap/snapcraft.yaml
The build failed due to missing `requests` build dependency, this patch
drops the unused component to build to avoid the problem.
The manpages are still built for the upcoming read-manual workaround.
=> fixup! Snap packaging improvements (#207)

snap/snapcraft.yaml
The selective-checkout scriptlet is only used during the build step, don't let it make into the final snap.
=> snap: Fix scriptlet leaked into the final snap

snap/snapcraft.yaml
Snap Store no longer supports Markdown's titled hyperlink markup [due to
its ugliness in the `snap info` output in the terminal][1], this patch
changes the description to reference style instead.
[1]:
https://forum.snapcraft.io/t/use-of-markdown-in-snap-metadata-summary-description/2128/23
=> description: Change hyperlink markup style

snap/snapcraft.yaml
Snapcraft now supports a special `core` base for modern snaps to target
on which has the same effect of using the Ubuntu 16.04 based `core` snap
in the past(it is special as the intended base snap to support Ubuntu
16.04 is rather the `core16` base snap, but it isn't ready yet).
This patch migrates the gallery-dl snap to `core` base, which allows the
user to avoid installing the additional `core18` base snap in order to
run it.  It also drops the redundant stage-packages entries that was
collected by Snapcraft automatically in the first place.
=> Migrate to core base

.travis.yml
> This PR should only be merged after #230 as the snap needs to target Ubuntu 16.04.
This ensure snap build-time and run-time problems will be noticed more
promptly by the maintainers, like issue #229.
=> Support snap building and simple testrun in Travis CI

snap/snapcraft.yaml
New Snap Store policy requires *-files interface plugs be named in a specific name.
Fixes #241.
Refer-to: The personal-files interface - doc - snapcraft.io <https://forum.snapcraft.io/t/the-personal-files-interface/9357>
Refer-to: The system-files interface - doc - snapcraft.io <https://forum.snapcraft.io/t/the-system-files-interface/9358>
=> snap: Use descriptive interface reference for *-files plugs

gallery_dl/extractor/instagram.py
Instagram has recently removed the `rhx_gis' in sharedData JSON
leading to extraction failures for tags and profiles.
Adjust `X-Instagram-GIS' header generation accordingly.
For completeness here the failure of the tests:
````
% env PYTHONPATH=. python3.7 test/test_results.py instagram
https://www.instagram.com/p/BqvsDleB3lV/
.
https://www.instagram.com/p/BoHk1haB5tM/
.
https://www.instagram.com/p/Bqxp0VSBgJg/
.
https://www.instagram.com/p/BtOvDOfhvRr/
.
https://www.instagram.com/explore/tags/instagram/
E
https://www.instagram.com/instagram/
E
======================================================================
ERROR: test_InstagramTagExtractor_1 (__main__.TestExtractorResults)
----------------------------------------------------------------------
File …
```
=> [instagram] Fix extraction after `rhx_gis' field removal

gallery_dl/extractor/instagram.py
Add support for Instagram user's stories
(https://www.instagram.com/stories/<username>/).
First the shared_data in instagram.com/stories/<username> is fetched in
order to retrieve the user_id that is then passed to fetch the stories
via the corresponding graphql query.
Please note that fetching stories is supported only when authentication
is enabled and the corresponding <username> is followed.
=> [instagram] Add support for stories

gallery_dl/extractor/twitter.py
Adds the functionality to download search results on twitter.com/search. Since twitter only allows downloading of up to 3,200 of a users most recent tweets, you will be unable to download old images from users with a lot of tweets. To bypass this, you can use the twitter search to get the tweets from the sections in time you were stopped at. An example search would be "from:user since:2015-01-01 until:2016-01-01 filter:images". The URL you would use will look something like this https://twitter.com/search?f=tweets&q=from%3Asupernaturepics%20since%3A2015-01-01%20until%3A2016-01-01%20filter%3Aimages&src=typd&lang=en
The _tweets_from_api function had to be changed because it would not get the next page of results using the last "data-tweet-id". It would return the same JSON but with a …
=> Add search downloading to twitter.py

docs/supportedsites.rst, gallery_dl/extractor/__init__.py, gallery_dl/extractor/realbooru.py
Realbooru uses the same version of booru as gel, so I used that extractor with changed variables, works perfectly.
=> [realbooru] Add Realbooru extractor

gallery_dl/extractor/twitter.py
Fix for https://github.com/mikf/gallery-dl/issues/544. Makes sure that it really reached the end by checking that both "min_position" is null and "has_more_items" is false before stopping.
=> [twitter] Fix stop before real end

gallery_dl/extractor/instagram.py
This add support for user's saved medias.  Please note that the user should be
authenticated and they can download only their saved medias (not other users
saved medias).
Close #643.
=> [instagram] Add support for user's saved medias

README.rst, docs/configuration.rst
Following my suggestions in #678 and #712
=> Some documentation improvements

gallery_dl/option.py
This fixes a small typo in the help text of an option.
=> Fix typo: defaut → default.

gallery_dl/extractor/__init__.py, gallery_dl/extractor/webtoons.py, scripts/supportedsites.py
The webtoons extractor can extract episode and entire comic (all
episodes) from webtoons.com.
All the logic of the extractors should be trivial except for a couple
of kludges needed:
- `ageGatePass' cookie is always set to avoid possible redirect and stop of
extraction, especially in the comic extractor
- The image URLs returned by the episode extractor could not be fetched
directly and the `Referer:' HTTP header needs to be passed to fetch them
Close #593.
=> [webtoons] Add a new extractor for webtoons.com

README.rst
I've been maintaining the Chocolatey package for [gallery-dl](https://chocolatey.org/packages/gallery-dl) for a bit now, and we're finally caught up with all released versions, and with that, think now it is a good time to list it as a supported install method in the readme.
=> README includes Chocolatey install method

gallery_dl/extractor/webtoons.py
Also use {comic} and {title_no} in the archive_fmt ({comic} can be the same for
multi-language comics but {title_no} seems different in these cases, so the
former could be helpful as a "text description" while the latter should make it
unique).
CLose #778
E.g.:
https://www.webtoons.com/en/romance/subzero/episode-35/viewer?title_no=1468&episode_no=40
https://www.webtoons.com/fr/romance/subzero/episode-35/viewer?title_no=1845&episode_no=38
=> [webtoons] make archive_fmt unique

README.rst, docs/configuration.rst, docs/gallery-dl.conf, docs/supportedsites.rst, gallery_dl/extractor/aryion.py, scripts/supportedsites.py
Implements login with username and password, instead of needing to export browser cookies.
While authentication is not absolutely required, posts on Eka's Portal can be made private or hidden from users who are not logged in.
=> [aryion] Add username/password support

docs/supportedsites.rst, gallery_dl/extractor/__init__.py, gallery_dl/extractor/weasyl.py
Closes #813
Supports individual posts, user galleries, folders, a journal, or all of a users journals. Uses the Weasyl API for everything but journals since there is no endpoint for that.
- Currently user extraction is an alias for submissions extraction but it could be made its own extractor for both submissions and journals. I feel like in general most people would just want the gallery if they fed in a username though.
- There might be someone that wants to download a favorites collection which is not a folder or gallery. There is no api for this so it would require iterating over the pages of the collection and grabbing the submits. If someone actually wants this its pretty trivial to implement but its a lot of non-API requests so I left it out for now.
- There is no way to filter by …
=> Weasyl Extractor

snap/snapcraft.yaml
Due to recent `snap info` command output changes selective-checkout no
longer can match the stable channel version, which, making it always
building stable releases even when it is being promoted to the stable
channel.
This patch fixes the problem by upgrading the part to the new version, which
now call the Snap Store API for the info instead of scraping `snap info gallery-dl`
command's output, which should ensure stability in the future.
Refer-to: Selective-checkout: Check out the tagged release revision if it isn't promoted to the stable channel - doc - snapcraft.io <https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617>
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> snap: Fix selective-checkout unable to build development snapshots

gallery_dl/extractor/reactor.py
Currently, the extractor doesn't work for URLs with no subdomain, such as http://reactor.cc/post/4525538.
This PR fixes it.
=> [reactor] match URLs without subdomain

gallery_dl/extractor/seiga.py, test/test_cookies.py
In niconico seiga, image page HTMLs are including metadata. I want to use metadata, so implemented. And fixed cookie check process.
=> [seiga] Support image metadata and fix cookie check.

docs/supportedsites.rst, gallery_dl/extractor/__init__.py, gallery_dl/extractor/photovogue.py
First contribution, there's probably something missing/not ideal. Let me know and I'll fix it. 😃
=> [photovogue] added portfolio extractor

gallery_dl/extractor/hentaifox.py
Groups on hentaifox lists the items to download the same way as the other pages (artists, search, tag, etc). But for some reason the extractor doesnt have group in the regex pattern to match against it. Added group to the pattern to search, and the test.
=> Add group to the HentaifoxSearchExtractor function

gallery_dl/extractor/__init__.py, gallery_dl/extractor/naverwebtoon.py, scripts/supportedsites.py
I've spend whole Sunday to add Extractor for [Naver webtoon](https://comic.naver.com). I made [scraper](https://github.com/sh-cho/k-webtoon-crawler) for this website so I'm pretty sure that I understand everything about this website.
I am not familiar with this project yet. I tried to make it work, but it doesn't seem to work.
Can you give me some advice?
=> Support naver webtoon

snap/snapcraft.yaml
The `personal-files` interface ~~autoconnect~~ request is [granted by the Snap Store](https://forum.snapcraft.io/t/interface-auto-connect-request-for-the-gallery-dl-snap-personal-files-netrc/20038/8).
Fixes #759.
=> [snap] allow access user's .netrc for site authentication

gallery_dl/__init__.py, gallery_dl/option.py
This change allows several input files to be specified, like this:
`gallery-dl -i file1.txt -i file2.txt`
If more than one file is specified, `main()` will iterate over the list of files and append the lines of one file after the previous one.
=> Adding handling of several input files

gallery_dl/extractor/weasyl.py
It's optional and requiring it forces users to escape those URLs because
of the ampersand
=> Weasyl: Drop the `&feature=submit` part of the favourite extractor URL

gallery_dl/extractor/pixiv.py
Output below is the matches of each URL in a list [uid, kind, self.tag, query], based on
https://github.com/mikf/gallery-dl/blob/91c2e15da9175c11ca2b9178dda20acf2e5eda5d/gallery_dl/extractor/pixiv.py#L300
Before:
```
https://www.pixiv.net/en/users/173530/bookmarks/artworks ['173530', 'bookmarks/artworks', None, None]
https://www.pixiv.net/bookmark.php?id=173530 [None, None, None, 'id=173530']
No match: https://www.pixiv.net/en/users/3137110
https://www.pixiv.net/bookmark.php?id=3137110&tag=%E3%81%AF%E3%82%93%E3%82%82%E3%82%93&p=1 [None, None, None,
'id=3137110&tag=%E3%81%AF%E3%82%93%E3%82%82%E3%82%93&p=1']
https://www.pixiv.net/bookmark.php [None, None, None, None]
https://www.pixiv.net/bookmark.php?tag=foobar [None, None, None, 'tag=foobar'] …
```
=> fix PixivFavoriteExtractor regex

gallery_dl/extractor/aryion.py
Without this you'll get paths like this:
- Starcross - Ch. 2 &quot;The Ins and Outs of Sarah&quot;
This commit changes it to:
- Starcross - Ch. 2 "The Ins and Outs of Sarah"
EDIT: haha nice, github auto-unescapes it, check message source for clarity ;)
=> [aryion] Unescape paths too

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/manganelo.py
Closes #676. Based on `mangakakalot` extractor, since they are similar.
I don't know how to get the hash of `content, url, keyword,...` for the test.
Help appreciated.
=> Add manganelo extractor

gallery_dl/extractor/webtoons.py
Fixes #1430 for me in Germany
I'm not sure if users in other GDPR countries (countries within the European Union) need localised cookies for this to work, nor do I know if this breaks downloads for people outside the EU.
=> [webtoons]: Add cookie rstagGDPR_DE=true

gallery_dl/extractor/gelbooru.py, gallery_dl/extractor/gelbooru_v02.py
extracting tag categories is currently broken on gelbooru (but not on other gelbooru-based sites) 
this fixes extraction and adds a test case
=> [gelbooru] fix tag category extraction

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/booru.py, gallery_dl/extractor/gelbooru.py, gallery_dl/extractor/gelbooru_v02.py
This PR adds an option to the booru extractors to extract the position and content of overlay notes:
I only implemented it for gelbooru for the time being, but it shouldn't be too hard to do other sites later.
=> [booru] add an option to extract notes (only gelbooru for now)

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/danbooru.py
This PR adds an option to danbooru to get additional metadata about notes, artist commentary, parent and children at the cost of one additional API request.
=> [danbooru] add option for extended metadata extraction

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/hentaicosplays.py, scripts/supportedsites.py
Hi, this is my first contribution.
This was requested but the issue seems to have been closed (#907)
https://hentai-cosplays.com have two sister sites which work exactly the same but contain different contents.
I put them in one extractor for now. 
If it's better to split them into 3 I'll be glad to work on it.
Cheers.
=> [hentaicosplays] Add extractor

gallery_dl/extractor/pixiv.py
A simple one. I want to save both the translated and untranslated tag versions from pixiv, so this change adds the untranslated tags when translated-tags is enabled. Save it into a separate entry instead of having pairs in "tags" to preserve backwards compat.
=> [pixiv] also save untranslated tags when translated-tags is enabled

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/fanbox.py, gallery_dl/extractor/fantia.py, scripts/supportedsites.py
Implemented post and user extractors for Fantia and Fanbox. Both use cookies for auth.
Doing it in 1 PR because these are pretty similar.
I added tests for both, however I don't know how to pass cookies to test_results.py so I didn't manage to run the Fantia tests.
The tests use freely available content, but registration (and for Fantia, subscription to the free plan) is likely needed.
Note that the test urls contain NSFW content (it's hard to find freely available + sfw on these sites).
Closes #849.
Closes #1260. 
Closes #739.
=> add extractors for fantia and fanbox

docs/configuration.rst, gallery_dl/extractor/pixiv.py
I want to download the top N posts from a ranking page where N is configurable. I did not find a way to do this (image-range is not good since a pixiv post may have many images). This PR adds an option to achieve this.
=> implement max-rank for pixiv

gallery_dl/extractor/mangapark.py
URLs like https://www.mangapark.net/manga/aria are redirected now to the v2 subdomain: https://v2.mangapark.net/manga/aria
This patch makes gallery-dl recognize these v2.mangapark URLs.
Looks like there is a "v3 beta" version of the site now, which has become the default. I don't really use the site so I did not investigate further compatibility with v3 beyond seeing that the URL formats are different. For now, the extractor seems to work fine with the v2 version.
=> recognize v2.mangapark URLs

gallery_dl/extractor/deviantart.py
To my knowledge, gallery-dl can download mature scraps from deviantart without cookies depsite the warning (see #1776 for details)
I haven't tested all the possible edge-cases yet (hence the PR being a draft). I'm putting this here mostly just to get used to pull requests
=> [Deviantart] [#1776] Remove the "you need session cookies to download mature scraps" warning

gallery_dl/extractor/__init__.py, gallery_dl/extractor/desktopography.py
Hello @mikf 
recently I stumbled upon this site: https://desktopography.net/ which host a variety of high quality wallpaper in different resolutions.
So I created an extractor for it.
It supports 
- the main site e.g. https://desktopography.net/
- a single yearly collection e.g. https://desktopography.net/exhibition-2020/
- a single entry (all the available sizes) e.g. https://desktopography.net/portfolios/new-era/ 
All files are saved as `name_resolution.ext`
I hope this is inline with the scope of the project.
If yes, upon review I expect the code to need to be cleaned up a bit.
Also, I'd appreciate some hints about what to do about the tests.
Thank you.
=> Desktopography extractor

gallery_dl/extractor/cyberdrop.py
Album IDs are random, organization would be much better having the album name then the identifier at the end
=> [CyberDrop] Change directory name format

docs/formatting.md
Adds the notes from https://github.com/mikf/gallery-dl/commit/0038a8c1a43eadad7f2d95dfc0856c805d5b8377 to the documentation. I changed 'extended' to 'special' for clarity.
Also, in the format specifier table, I changed 'before` and 'after' to 'start' and 'end' to keep this from happening:
Here's a direct link to the modified document:
https://github.com/ImportTaste/gallery-dl/blob/docs/formatting.md/docs/formatting.md#special-type-format-strings
=> Add special type format strings to docs

gallery_dl/extractor/webtoons.py
We'll be using this chapter as an example:
https://www.webtoons.com/en/thriller/school-bus-graveyard/episode-18/viewer?title_no=2705&episode_no=18
This neat trick actually comes from Webtoon's RSS feeds, where a
Referer header is unrealistic. Here's the RSS feed:
https://www.webtoons.com/en/thriller/school-bus-graveyard/rss?title_no=2705
They use URLs like this:
https://swebtoon-phinf.pstatic.net/20210929_12/1632867976494qzHhY_JPEG/16328679717202705189.jpg
The image links Webtoon's online client use URLs like this:
https://webtoon-phinf.pstatic.net/20210929_12/1632867976494qzHhY_JPEG/16328679717202705189.jpg?type=q90
Look familiar?
Yes, you only need to change the domain of your URL from
webtoon-phinf.pstatic.net to swebtoon-phinf.pstatic.net, a difference
of one character, to be able to …
=> [webtoons] Use swebtoon-phinf.pstatic.net instead of webtoon-phinf.pstatic.net

docs/formatting.md
Documents the environment variable syntax that was added in commit https://github.com/mikf/gallery-dl/commit/38193dba46ebb165290349d58d69c9711973aa86
=> Add environment variable syntax to formatting.md

gallery_dl/extractor/instagram.py
Currently the highlight extractor fails when there are more than 30 reel_ids supplied to the "/v1/feed/reels_media/" endpoint. 
For example, fetching highlights from "https://www.instagram.com/f1/" (87 highlights at the time I'm writing this)
```sh
gallery-dl -v --no-download -o include="highlights" "https://www.instagram.com/f1/"
```
will respond with status code 400.
Initially I tried splitting reel_ids into chunks of length 30, however, I quickly found that I consistently get 5xx responses when the total number of reel_ids is above 30 (I waited an entire week just to make sure that I wasn't being rate limited). When the total number of reel_ids is <= 30 (example account "https://www.instagram.com/bemytravelmuse/", 27 highlights at the time I'm writing this), you *can* fetch everything …
=> [instagram] fix highlights extraction

gallery_dl/extractor/common.py
Fix for Patreon Cloudflare issues by having only TLS v1.3 or higher establish HTTPS connections
This is based on the fact that there is another downloader that works fine and they indicate Cloudflare is triggered when TLS lower than 1.3 is used for it.  As of right now I tested on source and verified to trigger then made this one edit and it worked immediately after.  At this time can anyone else validate the change and see if Patreon starts working for you as well?  It is possible that once a TLSv1.3 connection is made from the client it stops triggering Cloudflare for a while as the normal version is working as well right now and it hasn't worked for quite a while.
=> Add option to disable tls 1.2

gallery_dl/extractor/common.py, gallery_dl/extractor/patreon.py
At the insistence of others, I updated the code a bit to disable TLS 1.2 by default on Patreon.  It is still a configurable option.
Should have really done this on the last PR but didn't think about it at the time.  Based on testing this should be good to go for Patreon.  Now people don't have to disable it manually in the config for Patreon.
Sorry to mikf since I know my last PR just got accepted recently.
=> [patreon] Disable TLS 1.2 by default

docs/gallery-dl-example.conf
- First example uses some custom options at the "gelbooru_v01" basecategory
These apply to all instances used herein
- Second example adds all options to the specific "gelbooru_v02" basecategory of TBIB
These settings are only used by TBIB
If I'm reading that correctly, that is 🤣 
Tested this locally with my own config, seems to work though.
=> Add two examples for custom instances of gelbooru

gallery_dl/extractor/reddit.py
While trying to download a submission on a user's personal page (these are submissions that are not bound to a subreddit but to an user, such as this one: https://www.reddit.com/user/TheSpiritTree/comments/srilyf/this_is_a_random_image_posted_for_automation/ ), I noticed that there was no sub-extractor of Reddit for this purpose (there is one for a whole user's page section, but not for single submissions)
This commit adds a class `RedditUserSubmissionExtractor` which takes care of this, providing the pattern for this situation.
Examples before then after the changes:
```
root@hestia:~ # python3 -m gallery_dl "https://www.reddit.com/user/TheSpiritTree" --verbose
[gallery-dl][debug] Version 1.20.4
[gallery-dl][debug] Python 3.7.3 - Linux-5.4.51-v7+-armv7l-with-debian-10.6 …
```
=> [reddit] Support of standalone submissions on personal pages of users

gallery_dl/extractor/fantia.py
This PR request aims to bring numerical ordering for filenames for the posts downloaded from Fantia in case there is more than one file in a single post.
=> Adding numerical ordering to fantia

gallery_dl/extractor/unsplash.py
When typing `hair style` in home page, the website will redirect you to https://unsplash.com/s/photos/hair-style. But when you roll down to get more images, it get data from https://unsplash.com/napi/search/photos?query=hair%20style where `-` is replaced with ` `.
=> [Unsplash] Fix UnsplashSearchExtractor by replacing dash with space

gallery_dl/extractor/twitter.py
fxtwitter.com is a service that somehow fixes twitter embeds on discord and other places. You simply replace twitter.com with fxtwitter.com when you post links in such services and you will get embeds. If you open the link, it will just redirect to twitter.com.
Recently I've seen a lot of people use this, so I think we should handle it here to avoid having to manually edit out the "fx" from URLs when passing to gallery-dl.
=> [twitter] accept fxtwitter.com URLs

docs/supportedsites.md, gallery_dl/extractor/photovogue.py
The old API server has an expired cert and they haven't update it since, because the frontend changed to the .com domain.
Also in general they set up redirects from the .it domain to the .com one and changed the routing a bit.
=> [photovogue] switch to .com, update api endpoint

gallery_dl/extractor/twitter.py
Now that fxtwitter.com fell out of favor/shut down, people switched to posting vxtwitter.com links (works the same as fxtwitter did).
I realize this is not a very scalable solution, so if other such sites pop up we might need a better way than just having the regex match them all, but for now it's probably still good enough.
=> recognize vxtwitter URLs

snap/snapcraft.yaml
=> [snap] Fix missing libslang dependency

docs/configuration.rst, gallery_dl/postprocessor/mtime.py, test/test_postprocessor.py
Closes #2721.
I'm not at all familiar with reStructuredText, so I based a lot of the doc changes on other options.
I'm also not sure if setting `self.value_fmt` and then setting `self._value_fmt` is necessary, again I saw another place where something similar was done so I went with it for now.
I was also considering wrapping the value of `mtime.key` in braces as the default format string for `mtime.value`, and using it as the only value for `mtime`. Currently it defaults to an empty string.
A review is welcome.
=> [postprocessor:mtime] add 'value' option

gallery_dl/extractor/twitter.py
=> [twitter] unescape content (#2756)

docs/supportedsites.md, gallery_dl/extractor/instagram.py
This adds support for user's saved collection medias, previously it would just download the user's entire saved medias.
=> [Instagram] Add support for user's saved collection

gallery_dl/extractor/mastodon.py
Most mastodon instances allow accessing ``/api/v1/accounts/XXXX/statuses`` and ``api/v1/statuses/XXXX`` without an API access token.
This pull request allows users to download at least some links from such a mastodon instance that does not already have access tokens hard-coded into the extractor.
User extractor only works on links that include the user id such as https://mastodon.tld/@id:12345. Status links work as-is.
Examples:
gallery-dl master:
``gallery-dl "mastodon:https://mastodon.improved-madness.de/@id:108302476900301707"``
```
[mastodon.improved-madness.de][error] Missing access token.
Run 'gallery-dl oauth:mastodon:mastodon.improved-madness.de' to obtain one.
```
using this pull request:
``gallery-dl "mastodon:https://mastodon.improved-madness.de/@id:108302476900301707"``
``` …
```
=> [mastodon] allow downloading without access token

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/oauth.py
There might be situations where you want to bind your oauth web server to something other than `localhost`.
F.e. if you use `gallery-dl` in a docker environment and you want to expose the oauth port to its network, there is  currently no way as you need to bind the host to `0.0.0.0` to be able to forward ports.
=> [oauth] add host config option

gallery_dl/extractor/tumblr.py
=> [tumblr] add count metadata field

docs/configuration.rst, gallery_dl/extractor/tumblr.py
=> [tumblr] attempt to fetch high-quality inline images

docs/configuration.rst, docs/gallery-dl-example.conf, docs/gallery-dl.conf, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/nana.py, scripts/supportedsites.py, test/test_results.py
=> [nana] add nana extractor

gallery_dl/extractor/exhentai.py, gallery_dl/job.py
I'm using gallery-dl as a library and I've created a custom job for metadata extraction, similar to `DataJob`. But I was getting identical metadata for different pages on ExHentai. Digging a bit deeper, here's what I've found.
`ExhentaiGalleryExtractor.items` yields the same object for each image in a gallery. This causes problems when the object is not immediately used.
To reproduce:
```bash
gallery-dl --dump-json https://e-hentai.org/g/2346908/ab876a4073/ -o output.private=true
```
`-o output.private=true` causes image `kwdict` to be passed through `util.identity` in `DataJob.handle_url`:
https://github.com/mikf/gallery-dl/blob/560f7b41d80a07d6f711ede2246524ab064d38a1/gallery_dl/job.py#L700
https://github.com/mikf/gallery-dl/blob/560f7b41d80a07d6f711ede2246524ab064d38a1/gallery_dl/job.py …
=> Fix rare ExHentai duplicated metadata bug

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/smugloli.py
https://smuglo.li/
https://smugloli.net/ [mirror]
=> [smugloli] add smugloli extractors

docs/supportedsites.md, gallery_dl/extractor/danbooru.py, test/test_results.py
Adds support for aibooru.online, a danbooru-based site.
One difference from the main danbooru site is that for whatever reason, aibooru returns relative URLs, e.g.
on danbooru you have in `post`:
'file_url': 'https://cdn.donmai.us/original/3c/1a/3c1a2a04a6060c497b714b9007a8331f.png'
while on `aibooru`:
'file_url': '/data/original/0c/54/0c540b58dc26913e77d86e318b0552d4.png'
The added check aims to detect and fix this situation.
=> add support for aibooru (using danbooru extractor)

gallery_dl/extractor/gelbooru.py
The regex currently implemented wouldn't support urls where the `s, page, and id` orders were different. 
placing `page=post` and `s=view` into look-aheads from the `?` forward allows for any order while also checking if present.
URLs tested
```
1: https://gelbooru.com/index.php?page=post&s=view&id=7583325
2: https://gelbooru.com/index.php?page=post&s=view&id=7583325&tags=cat
3: https://gelbooru.com/index.php?id=7583325&page=post&s=view
```
Match 2 was gotten by searching for 'cat' and then clicking on an image. Seems gelbooru embeds search parameters
Old regex
```
(?:https?://)?(?:www\.)?gelbooru\.com/(?:index\.php)?\?page=post&s=view&id=(?P<post>\d+)
```
Results:
1: Match: `https://gelbooru.com/index.php?page=post&s=view&id=7586232`, Group post: `7586232`
2: Match: …
=> [gelbooru] regex for extractor not allowing alternate parameter order in url.

gallery_dl/util.py
- Allows gallery-dl to ignore other columns in the archive database, provided they don't have the `NOT NULL` constraint
- Sets type affinity to `TEXT`. When integers are stored as text, both `SELECT 1 FROM archive WHERE entry=123` and `SELECT 1 FROM archive WHERE entry='123'` will return `true`.
=> Improve compatibility of DownloadArchive

docs/supportedsites.md, gallery_dl/extractor/mangasee.py, scripts/supportedsites.py
=> [mangasee] add support for 'mangalife'

gallery_dl/extractor/vichan.py
``` bash
$ py -m gallery_dl -s https://smugloli.net/a
[gallery-dl][error] No suitable extractor found for 'https://smugloli.net/a'
```
=> [vichan] recognize board url w/o trailing slash

gallery_dl/extractor/moebooru.py
related to #3093 
```
$ py -m gallery_dl -K https://lolibooru.moe/post/show/281305/ -o "notes=True"
notes[translation][]
- Heheh
- I'm the tallest one here.
- Ah, then again... Perhaps it's because I'm wearing boots.
- It seems that I'm the taller one?
```
---
- maybe instead of `notes[translation][]`, a simple `notes_translation[]` be enough for this
- I have separated the \<p\> tags using `space`, but the website uses `\n\n`
=> [moebooru] extract 'notes'

gallery_dl/extractor/instagram.py
#3076 inadvertently introduced an AttributeError on extracting URLs like `https://www.instagram.com/stories/<username>`. This PR defaults the attribute to `None`.
=> [instagram] Fix AttributeError on user stories extraction

gallery_dl/extractor/mastodon.py
Example usage:
If the url is ```mastodon:https://social.linux.pizza/@unicodeplus@botsin.space``` 
the "remote_instance" will be "botsin.space". 
```"directory": ["mastodon", "{instance_remote|instance}", "{account[username]!l}"]```
=> [mastodon] add "instance_remote" field

gallery_dl/extractor/twitter.py
Twitter changed the URL format to access tweet data through their syndication API.
=> [twitter] update URL for syndication API

gallery_dl/extractor/reddit.py
resolves #3258 
syntax is slightly awkward due to flake8 E501 constraints but it works just fine
=> use dash_url for reddit_video to fix issue 3258

gallery_dl/extractor/hitomi.py
A webp fallback was introduced after I made aware of it in a github issue, but it does not check every image. As an example, an image sequence like `avif, webp, avif, webp, webp, avif`, would download incorrectly, or rather, skip all webp due to broken links. The first image is avif, it passes and then tries to download everything as avif, but avif does not exist for every image. An avif property check for every image is needed, since not all files have the same file format in one gallery.
=> [hitomi] applying avif check for every image (#3030)

docs/configuration.rst, gallery_dl/job.py
An updated implementation of #3062. As with other `*-metadata` options, I've made this one extractor-specific and disabled it by default (the verbose log should be sufficient for bug reporting).
=> Implement `version-metadata` option

gallery_dl/extractor/sexcom.py
The format of video sources was changed recently to be a full URL with https:// in the beginning. The original extractor code appended the video source URL to root url of the website, thus yielding invalid url in format ...sex.comhttps... that failed to resolve.
Closes #3408
=> [sex.com] Download videos from cdn (#3408)

docs/configuration.rst, gallery_dl/extractor/danbooru.py
Sometimes the number of returned `post` objects is smaller than the per-page limit even though there are more posts. This causes gallery-dl to stop the pagination prematurely.
[Example JSON](https://e621.net/posts.json?tags=zootopia+rating%3Asafe+status%3Adeleted&limit=320)
The API returns 318 posts.
This only seems to apply to deleted posts. Not sure if other Danbooru instances are affected as well.
=> [e621] implement manual pagination

gallery_dl/extractor/deviantart.py
URLs I found when searching for `deviantart.com/view` on web.archive.org:
- `https://www.deviantart.com/view/<id>`
- `http://` redirects you to `https://`
- `deviantart.com` redirects you to `www.deviantart.com`
- One trailing slash in the URL is ignored
- If the deviation exists, it redirects you to `https://www.deviantart.com/<username>/<art|journal>/<id>`
- If no deviation exists, it sends a 404
- There are some URLs with an `offset` parameter, e.g. https://www.deviantart.com/view/14864502/?offset=80 ([wayback machine](https://web.archive.org/web/20211110113021/https://www.deviantart.com/view/14864502/?offset=80)), don't know what it means
- `https://www.deviantart.com/view.php?id=<id>`
`https://www.deviantart.com/view-full.php?id=<id>`
- `http://` redirects you to `https://`
- …
=> [deviantart] add /view URL support

docs/configuration.rst, gallery_dl/extractor/twitter.py
The syndication API doesn't return as much metadata as the GraphQL API, so I've implemented `syndication=extended` to enable the user to optionally fetch user metadata using `user_by_screen_name`. This is mostly useful when used along with `conversations`, `retweets`, etc.
=> [twitter] implement `syndication=extended`

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/tcbscans.py, scripts/supportedsites.py
=> [tcbscans] add 'chapter' and 'manga' extractors

docs/configuration.rst, gallery_dl/extractor/twitter.py
Resolves https://github.com/mikf/gallery-dl/issues/3439 (although this is technically a separate issue).
See also: https://github.com/mikf/gallery-dl/issues/3439#issuecomment-1364449560, https://github.com/mikf/gallery-dl/commit/1d14928bd9f979a5a5c3d77cf3fdb0d25a0d99e1
=> [twitter] apply tweet type checks before uniqueness check

docs/configuration.rst, gallery_dl/formatter.py
No function changes.
Update links which refer to common.py, job.py and extractor.py to show correct line numbers.
Slighty update formatter.StringFormatter conversions docstring.
=> [docs] Update links and fix field typo

gallery_dl/extractor/myhentaigallery.py
There is for some reason a space before the `<h1>` tag on some pages, for example [this one](https://myhentaigallery.com/gallery/thumbnails/8901), which makes the extractor fail.
=> [myhentaigallery] handle whitespace before the title tag

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/wikifeet.py, scripts/supportedsites.py
closes #519
https://pics.wikifeet.com/Scarlett-Johansson-Feet-5015785.jpg (browser)
https://pics.wikifeet.com/Scarlett_Johansson-Feet-5015785.jpg
Both of these are valid URLs, but maybe I should do `.replace("_", "-")` and not differ from what the browser gives.
=> [wikifeet/wikifeetx] add 'gallery' extractor

gallery_dl/extractor/twitter.py
Fixes #3536. The strange results were caused by the search API defaulting to the 'Top' feed. I have no idea why `tweet_search_mode` triggered 401 errors several days ago, but now it seems to be working again.
=> [twitter] fix search (#3536)

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/deviantart.py, scripts/supportedsites.py
Partially resolves #3539
1/3 done
=> [deviantart] add extractor for status updates

gallery_dl/extractor/generic.py
Trying something like `gallery-dl -g "generic:https://boards.4channel.org/vt/thread/41385493" --filter "re.match('(https://i\.4cdn\.org/vt/[0-9]+\.)|(https://(litter|files)\.catbox\.moe/)',imageurl)"`
you can see that the catbox URLs have some `<wb` trash at the end, caused by not stopping the regex match at `<` characters. This is an attempt to fix that.
=> [generic] fix regex for non-src image URLs

gallery_dl/extractor/deviantart.py
=> [deviantart] add support for /deviation/ and fav.me URLs

gallery_dl/extractor/bunkr.py
The bunkr extractor special cases a bunch of file extensions because bunkr itself has a streaming player for those extensions. Turns out mkv and ts files should also be included.
=> [bunkr] Fix extracting mkv and ts files

gallery_dl/extractor/imagehosts.py
phun.imagetwist.com and imagehaha.com domains are just aliases for imagetwist.com, so i added them to the pattern of the existing extractor
=> [imagetwist] add phun.imagetwist.com and imagehaha.com support

gallery_dl/extractor/deviantart.py
Example:
```json
"items": [
{
"type": "deviation",
"deviation": {
"deviationid": "147C8B03-7D34-AE93-9241-FA3C6DBBC655",
"printid": null,
"is_deleted": true
}
}
],
```
This deviation isn't actually deleted and can be fetched as usual using the `deviation` endpoint.
I've been working on several features and bugfixes for DA extractors and this is one of them. Unfortunately they are **heavily** intertwined with each other, so I'm trying my best to separate them into branches and reduce the overall complexity.
Known issues:
* If there are sta.sh-ed deviations in `items` and `extra` is enabled, these deviations will be extracted twice
* `metadata` and `folders` doesn't work for deviations in `items`
* If there are duplicate deviations, the `deviation` endpoint will be called multiple times …
=> [deviantart] fix crash when handling deleted deviations in status updates

gallery_dl/postprocessor/metadata.py, test/test_postprocessor.py
See this issue: https://github.com/mikf/gallery-dl/issues/3674
The following command will fail on current master:
`gallery-dl --ignore-config --write-tags --option "extractor.pixiv.tags=original" --verbose https://www.pixiv.net/en/artworks/105480642`
The traceback:
```
File "/Users/gray/source/gallery-dl/gallery_dl/job.py", line 102, in run
self.dispatch(msg)
File "/Users/gray/source/gallery-dl/gallery_dl/job.py", line 146, in dispatch
self.handle_url(url, kwdict)
File "/Users/gray/source/gallery-dl/gallery_dl/job.py", line 297, in handle_url
callback(pathfmt)
File "/Users/gray/source/gallery-dl/gallery_dl/postprocessor/metadata.py", line 101, in run
self.write(fp, pathfmt.kwdict)
File "/Users/gray/source/gallery-dl/gallery_dl/postprocessor/metadata.py", …
```
=> [pixiv] Fix tag write when tags setting is set to original

gallery_dl/extractor/directlink.py, gallery_dl/extractor/generic.py
Edit: https://räksmörgås.josefsson.org/ doesn't produce a reliable hash. I have no idea why sometimes I get `c305a94c413da6280b0b7bfe5e33d7f527028c9f` instead of `af05612771596353fefcc800ed4a77571e0f1c09`.
=> [generic] add support for internationalized domain names

gallery_dl/extractor/deviantart.py
`fxdeviantart.com` ([source code](https://github.com/robinuniverse/fxdeviantart)) is a service that fixes embeds on Discord, similar to `fxtwitter.com`. It'd be nice to be able to feed URLs directly to gallery-dl without having to strip the prefix manually.
It currently does not support the following URLs:
```
https://foo.fxdeviantart.com/art/1234567890
https://www.fxdeviantart.com/view/1234567890
https://www.fxdeviantart.com/deviation/1234567890
```
dA's oEmbed API does accept such URLs, so this is most likely a bug.
=> [deviantart] add support for fxdeviantart.com URLs

gallery_dl/extractor/hotleak.py
E.g. `hot4lexi` would start downloading the `hot` section by mistake
This happened because the regex had a negative lookahead for the category names, but didn't ensure that they where followed by either end-of-string or a slash.
=> [hotleak] Fix downloading of creators whose name starts with a category name

docs/configuration.rst, gallery_dl/downloader/http.py
* fix connection not being released when the response is neither successful nor retried
This can be reproduced using the following command:
```
> gallery-dl -v https://example.org/foo.png https://example.org/bar.png
[gallery-dl][debug] Version 1.25.0-dev - Git HEAD: c9a73452
[gallery-dl][debug] Python 3.10.0 - Windows-10-10.0.19044-SP0
[gallery-dl][debug] requests 2.26.0 - urllib3 1.26.7
[gallery-dl][debug] Configuration Files []
[1/2] https://example.org/foo.png
[gallery-dl][debug] Starting DownloadJob for 'https://example.org/foo.png'
[directlink][debug] Using DirectlinkExtractor for 'https://example.org/foo.png'
[urllib3.connectionpool][debug] Starting new HTTPS connection (1): example.org:443
[urllib3.connectionpool][debug] https://example.org:443 "GET /foo.png HTTP/1.1" 404 648 …
```
=> [downloader:http] add 'consume-content' option

gallery_dl/extractor/pixiv.py
Added the popularity sorting modes to the tag search downloader.
This requires pixiv premium on the account used for downloading (I have premium and verified these parameters work).
=> [pixiv] allow sorting by popularity (requires pixiv premium)

gallery_dl/extractor/reddit.py
The previous if statements determining the type of a submission would ignore video and gallery submissions if the post was cross posted, resulting in the submission url getting ignored and marked as unsupported.
Changed the if checks to be similar to the if check for image posts. Also had to get the gallery data of a post from its parent post (which is already present in the submission in the `crosspost_parent_list` attribute) since it doesn't exist in the base submission object.
Video cross-post example: https://www.reddit.com/r/kittengifs/comments/12m0b8d/the_cutest_handful/
Gallery cross-post example (took some time to find): https://www.reddit.com/r/MinecraftBedrockers/comments/130vufu/for_some_reason_i_permanently_have_a_cursed_water/
Closes …
=> [reddit] fix extraction for cross-posted reddit videos and galleries

gallery_dl/extractor/8muses.py
This fixes 8muses album URL formatting, and adds the permalink and its parts to the album object to improve directory formatting flexibility.
For example, this allows the following configurations to work. Using `/comics/album/Fakku-Comics/mogg/Liar` test URL:
```json5
{
"extractor":
{
"8muses":
{
// Sets path-restrict to allow slashes in album data to create subdirectories (semi-unsafe)
// Writes to: 8muses/Fakku-Comics/mogg/Liar
"path-restrict": "\\\\|<>:\"?*",
"directory": ["{category}", "{album[permalink]}"],
},
"8muses":
{
// Writes to: 8muses/Fakku-Comics/mogg/Liar
"directory": ["{category}", "{album[parts][0]}", "{album[parts][1]}", "{album[parts][2]}"]
},
"8muses":
{
// Similar to default path but with a top-level artist/publisher directory
// Writes to: 8muses/Fakku-Comics/Fakku …
```
=> [8muses] Add permalink + parts to album data

gallery_dl/extractor/imagehosts.py
Extractor was broken because the pages now use double quote around attributes.
=> [acidimg] fix extractor

gallery_dl/extractor/jpgfish.py
The domain jpg.pet is just an alias for the existing jpgfish module.
=> add jpg.pet as alias for jpgfish

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/jschan.py, scripts/supportedsites.py
This is similar to the generic Lynxchan extractor that was added recently (#3394).
=> [jschan] add generic extractor for jschan imageboards

gallery_dl/extractor/danbooru.py
add support for another danbooru instance.
right now as I open this PR i realized it's possible to add custom danbooru instances from the config, just have to use "Danbooru" category instead of "danbooru" which i was trying.
Since I already made a commit for this, I'll leave it up to you if you want to add another site to the defaults or not. Feel free to close this PR if not.
=> [danbooru] add support for booru.borvar.art instance

gallery_dl/extractor/bunkr.py
Somewhat recently, Bunkr migrated the content of the cdn9 media server to a new host. With the migration, they gave it a new domain; the old domain now just returns 502. This PR adds a mapping for that domain, similar to the special case for cdn12.
Only manually tested so far, using the public album list to find an album. I don't have a bunkr account to upload suitable (small, SFW) test files - if you do, feel free to edit the PR to add a test case.
Fixes #4386
=> [bunkr] fix media domain for cdn9

gallery_dl/extractor/bunkr.py
The Bunkr extractor already had support for a number of file extensions that Bunkr hosts on a separate CDN. This PR adds another one, `.wmv`. I also found a few cases of files like `foo.MOV` which weren't being handled correctly, so this PR also updates the check to be case-insensitive.
=> [bunkr] Fix extracting wmv files

gallery_dl/extractor/imgbb.py
Just noticed this while extracting some albums.
Seems to fix it, of course, feel free to make any changes / adjustments etc.
=> [imgbb] Fix `user` extraction, add `displayname`

docs/supportedsites.md, gallery_dl/extractor/reddit.py, test/results/reddit.py
Reddit Mobile app has implemented a new share URL format relatively recently (somewhere around August), which looks like this:
https://www.reddit.com/r/analog/s/hKrTTvFVwZ
This is an obfuscated personalized tracking URL which redirects to a submission:
https://www.reddit.com/r/analog/comments/179exao/photographing_the_recent_annular_eclipse_with_a/?share_id=okPOBW_OzrDClMSiZSLjV&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1
This PR adds a minimal redirect extractor for this URL format.
=> [reddit] implement Reddit Mobile share links

gallery_dl/extractor/4archive.py, gallery_dl/extractor/__init__.py, test/results/4archive.py
closes https://github.com/mikf/gallery-dl/issues/1262, https://github.com/mikf/gallery-dl/issues/2418, https://github.com/mikf/gallery-dl/issues/4400, https://github.com/mikf/gallery-dl/issues/4710
slightly different from [4chanarchives](https://github.com/mikf/gallery-dl/blob/master/gallery_dl/extractor/4chanarchives.py)
=> [4archive] add 'thread' and 'board' extractors

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/tmohentai.py
For site-request #4808. You can pass the main content URL or any individual page URL. No support for groups or tags as of right now (I can work on adding them if someone will find it useful).
I'm open to any feedback, particularly the metadata retrieval.
=> [Tmohentai] add support

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/urlgalleries.py
For #919, #1184, #2905
Gallery image urls redirect to a hosting site:
gallery url - `https://beautiesonearth.urlgalleries.net/porn-gallery-6915206/gemma-arterton-%2a100-streets%2a-premiere-in-london-nov-8`
image url - `https://beautiesonearth.urlgalleries.net/gemma-arterton-+100-streets+-premiere-in-london-nov-8-w59n0dk3qy.jpg`
image url forwards to - `https://pixhost.to/show/952/35141831_dcotqomb.jpg`
The extractor needs corrected to follow the redirect, work in progress. Right now it saves the image host source code as an image file.
=> [urlgalleries] add support

gallery_dl/extractor/patreon.py
TLDR: `window.patreon = {"bootstrap":'` did not work anymore. Change it to `window.patreon = wrapInProxy({"bootstrap":`
Feel free to change, approve or deny it.
=> Fix for "[patreon][error] Unable to extract bootstrap data #4904"

docs/supportedsites.md, gallery_dl/extractor/shimmie2.py, scripts/supportedsites.py, test/results/rule34hentai.py
updates shimme2.py to allow rule34hentai support. a seperate _posts_rule34hentai function was needed since the base extractor method for posts does not work with it.
=> [rule34hentai] add support

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/bato.py, scripts/supportedsites.py, test/results/bato.py
I only added Bato.to v3x (version 3) support, but no v2x. Not sure how you want to handle that - I'm thinking a new v2x extractor that just prints an error and tells the user to use a v3x link.
Closes #2111 and affects #1434.
=> [bato] add support

gallery_dl/extractor/__init__.py, gallery_dl/extractor/zzup.py, test/results/zzup.py
closes #4517, #4659, #4863
`ZzupImageExtractor` is possible but would require 1 additional request, or by `.replace("_", " ")` the slug.
=> [zzup] add 'gallery' extractor

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/hatenablog.py, scripts/supportedsites.py, test/results/hatenablog.py
=> [hatenablog] add support

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/steamgriddb.py, scripts/supportedsites.py, test/results/steamgriddb.py
If invalid sorting/filtering options are sent to the server, the server responds with a 500 and `{"message": "Slim Application Error"}`.
Fixes #5033
=> [steamgriddb] add support

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/wikimedia.py, scripts/supportedsites.py, test/results/wikibooks.py, test/results/wikimediacommons.py, test/results/wikinews.py, test/results/wikipedia.py, test/results/wikiquote.py, test/results/wikisource.py, test/results/wikispecies.py, test/results/wikiversity.py, test/results/wiktionary.py
This is related to the issue https://github.com/mikf/gallery-dl/issues/1443
I wrote an extractor for Wikipedia and Wikimedia.
This is a first version that supports:
- extracting images from an article, examples:
```
https://en.wikipedia.org/wiki/Athena
https://zh.wikipedia.org/wiki/太阳
https://simple.wikipedia.org/wiki/Hydrogen
```
- extracting images from a category, examples:
```
https://commons.wikimedia.org/wiki/Category:Network_maps_of_the_Paris_Metro
https://commons.wikimedia.org/wiki/Category:Tyto_alba_in_flight_(captive)
```
Metadata are extracted from the items and passed accordingly to the downloader.
Since I do not have a 100% view of the codebase and process, do not hesitate to advise if there is something in this code that could be done better. I am thinking particularly to …
=> [wikimedia] Add Wikipedia/Wikimedia extractor

gallery_dl/extractor/blogger.py
Some URLs use "lh(number)-(locale).googleusercontent.com" format, so I added support for those.
Also, "lh(number).googleusercontent.com" formats were broken because the regex was looking for a second forward slash.
Examples:
lh7.googleusercontent.com
lh7-us.googleusercontent.com
=> [blogger] Fix lh*(-**).googleusercontent.com URLs

gallery_dl/extractor/skeb.py
Not exactly a fan of `datas` and `data`, but not exactly a fan of `data` and `datum` either.
=> [skeb] add 'num' and 'count' metadata fields

gallery_dl/extractor/pornpics.py
In some cases gallery has multiple channels, adding extra field as to not break backwards compatibility.
=> Add support for multi channels

Dockerfile
Reduce a layer, update pip and apk, and reduce increased image size by optimization.
The previous image size is approximately 247 MB. With this PR, 244 MB
Without the code below
```
python3 -m pip install --no-cache-dir -U pip  && \
```
the image will be 10MB smaller.
=> Dockerfile/chore: Update Dockerfile

gallery_dl/extractor/naver.py, test/results/naver.py
Around October 2016, the image server URL format and file name encoding changed from EUC-KR to UTF-8. Modified to detect old URL format and decode image URLs into EUC-KR
=> [naver] EUC-KR encoding issue in old image URLs

gallery_dl/extractor/mastodon.py, test/results/mastodon.py
Examples:
- https://wanderingwires.net/@quarc/9qppkxzyd1ee3i9p
- https://void.rehab/@mia/9qqz5hl5yauvqwq5
- https://transgirl.cafe/@izzie/9octesgee0tz01ov
=> [mastodon] fix handling null 'moved' account field

gallery_dl/extractor/instagram.py
I don't know when/why this happens and for private account reasons can't add an example here, but i had this error out and it feels like a safe fix to default to `0` here.
=> [instagram] default posts `like_count` to zero

gallery_dl/extractor/twitter.py, test/results/twitter.py
=> [twitter] fix pattern for single tweet (#5371)

gallery_dl/extractor/common.py
If gallery-dl fails to write updated cookies, for example because the disk is full, on some systems it leaves behind an empty file, wiping out the existing cookies. To fix this, write the updated cookies to a temporary file first, then rename over the original cookies file.
=> [generic] use tempfile when saving cookies

gallery_dl/__init__.py, gallery_dl/option.py
This commit adds a warnings flag
It can be combined with -q / --quiet to display warnings. The intent is to provide a silent option that still surfaces warning and error messages so that they are visible in logs.
I'm not entirely sure if this is the best approach or if there's already an existing way to accomplish this but with this I can run `gallery-dl -q -w` and I get silent output but still see warnings.  Essentially, I want an option that's in-between -q and -v, -v is too noisy. I only want to see warning messages and error messages.
=> Add warnings flag

gallery_dl/extractor/mastodon.py
According to the mastodon API documentation the `only_media` and `exclude_replies` parameters must be boolean:
> only_media
Boolean. Filter out statuses without attachments.
exclude_replies
Boolean. Filter out statuses in reply to a different account.
https://docs.joinmastodon.org/methods/accounts/#query-parameters
The current implementation passes them as integers which causes issues with other services that implement the mastodon API, in my case Mitra instances.
=> [mastodon] Use boolean instead of integer keys for accounts/statuses endpoint

gallery_dl/cookies.py
When reading cookies from the browser, the user is able to give either just the browser name, or also provide profile/container information.
If an exact profile is provided, there is no need to find the latest profile with `os.walk` which is very expensive.
This change optimizes that case and the performance increase is significant (~8 sec to 0.6 sec).
```
$ time gallery-dl --config-ignore -d . -D . --cookies-from-browser FIREFOX https://imgur.com/OO4UNqJ
[cookies][info] Extracted 16 cookies from Firefox
./imgur_OO4UNqJ.jpg
real    0m8.429s
user    0m0.216s
sys     0m0.431s
$ time gallery-dl --config-ignore -d . -D . --cookies-from-browser FIREFOX:bgamf5r6.default-release https://imgur.com/OO4UNqJ
[cookies][info] Extracted 16 cookies from Firefox
./imgur_OO4UNqJ.jpg
real    0m0.456s
user …
```
=> optimize _find_most_recently_used_file for exact profile

gallery_dl/extractor/twitter.py, test/results/twitter.py
Those can be spotted when opening or copying links from the Media tab of an account.
=> [twitter] Match "/video/" Tweet URLs

gallery_dl/extractor/instagram.py
Background and context:
1. Instagram by default requires you to be logged in.
2. Your account can LIKE posts.
3. Getting all of your likes from IG can be a pain.
As an active IG user, I want to be able to download only posts I've liked.
The information of whether or not your logged-in user has liked the target post is available in the API results, but was not available to the end-user for filtering.
This small change allows `user_has_liked` to be used to e.g. download only liked posts of an entire IG account.
Example use:
```
$ gallery-dl --filter 'user_has_liked' https://www.instagram.com/imgur/
```
This will only download the posts that have `has_liked: True` set in the returned REST API data.
Note: it will still need to loop through the entire account's posts since this is done …
=> Enable `user_has_liked` as IG download filter

gallery_dl/extractor/speakerdeck.py
Current HTML of speakerdeck is like 
```html
<div class="sd-player-slide js-sd-slide"
data-url="http://...
```
So, the current extractor does not work because it can not handle line breaks and leading spaces.
With this PR,  the extractor can simply ignore them.
=> fix: extractor for speakerdeck.com

docs/supportedsites.md, gallery_dl/extractor/tcbscans.py, test/results/tcbscans.py
=> [tcbscans] support other domains

gallery_dl/extractor/subscribestar.py
Very basic solution to the bug where gallery-dl does not parse correctly the date on updated posts because of the "Updated on " prefix. This simply detects and remove the prefix before the parsing.
=> Fix subscribestar date parsing in udated posts

gallery_dl/extractor/twitter.py
By running `gallery-dl` with `--write-pages` and examining the page items, I noticed the Twitter response actually does contain the bookmark count and the view count for each tweet, which was not previously being extracted.
This fixes #5482
=> [twitter] Add `bookmark_count` and `view_count`

gallery_dl/extractor/aryion.py
Fixes #4511
I tried my best without a lot of python experience, I hope this is good enough to close the issue.
The `path` keyword won't match the path in the favorite gallery, but the original path in the artists gallery. I'm not sure of what the best solution would be, but I'm not too bothered by it right now
=> [aryion] Add favorite extractor

gallery_dl/extractor/imagefap.py
Imagefap.com assigns (random?) numeric filenames to all of their images.  This means that the current default effectively shuffles each gallery randomly upon download.
The original filenames are listed on the gallery page below the corresponding images, but extracting those is a lot more work than just numbering the images.  This tiny fix will at least preserve the gallery ordering if not the original uploaded filenames and (IMHO) is a strict improvement on the existing default.
Fixes #1746
=> Numbers images obtained from imagefap by default.

gallery_dl/extractor/pixiv.py
i think this should fix can not download R-18 series in pixiv
for illust_series api i just guess url and lucky to find it.
=> [pixiv] use api for illust series

gallery_dl/extractor/e621.py
It's quite common to encounter multiple posts from the same pool when downloading tags from e621. Currently when the `pools` option is enabled, gallery-dl will make a web request every time it encounters such a post.
This PR reduces the number of API requests (and also makes the download job slightly faster) by memcaching API calls to `/pools.json`.
=> [e621] cache pool metadata API calls

docs/configuration.rst, gallery_dl/extractor/wikimedia.py, test/results/fandom.py, test/results/wikipedia.py
This PR adds the ability to download all media files hosted on a MediaWiki instance.
=> [wikimedia] add 'wiki' extractor

gallery_dl/extractor/flickr.py
This PR fixes a bug introduced in https://github.com/mikf/gallery-dl/commit/e92a9ae34389bb1d429b75ee981dde770b962b36#diff-5741d04464e95eab8716d83190078fd31be0ad91fed8da24cd390b9447239d35R522.
Before the referenced commit, [the code read `photo.update(self.api.photos_getAllContexts(self.item_id))`](https://github.com/mikf/gallery-dl/commit/e92a9ae34389bb1d429b75ee981dde770b962b36#diff-5741d04464e95eab8716d83190078fd31be0ad91fed8da24cd390b9447239d35L81). After the commit, the code became the same ([see how the EXIF-related code above was updated correctly](https://github.com/mikf/gallery-dl/commit/e92a9ae34389bb1d429b75ee981dde770b962b36#diff-5741d04464e95eab8716d83190078fd31be0ad91fed8da24cd390b9447239d35R514)), referencing `self.api`, which doesn't exist in this new context, which …
=> [flickr] reference the correct function

gallery_dl/extractor/generic.py, test/results/generic.py
Adds better fields which can be used in the config like `path` (url path) or `subcategory` (domain).
Note: Changes the default directory_fmt to use those.
Before:
```
./gallery-dl/generic/https:__www.nongnu.org_lzip_/lzip.png
```
After:
```bash
./gallery-dl/generic/www.nongnu.org/lzip/lzip.png
```
=> [generic] better directory formatting/md

gallery_dl/extractor/weasyl.py, test/results/weasyl.py
When you click favourites on Weasyl, it tends to go to the clean URL format:
https://www.weasyl.com/favorites/furoferre
Rather than the user ID format. 
The user ID format still works, but you click "more submissions" to get there:
https://www.weasyl.com/favorites?userid=184616&feature=submit
This change allows the extractor to use the clean URL format, as well as the user ID format. It just uses the first to get the user ID for the second.
I did notice btw that some accounts have character favourites and things, alongside submission favourites, for example this account just has character favourites:
https://www.weasyl.com/favorites/jaggy
and those are listed with `feature=char`:
https://www.weasyl.com/favorites?userid=12345&feature=char
But the weasyl extractors don't have support for …
=> [weasyl] Fix favourites extractor and add support for the readable URL format

gallery_dl/extractor/inkbunny.py
This little PR changes where Inkbunny images download, so they download into the directory of the user whose favourites are being downloaded, rather than in different directories for each submission. This makes it better match the favorites download for FA, and twitter and similar. (And matches the changes for Weasyl in #6113 )
=> [inkbunny] Store Inkbunny favourites in the Favorites directory of the user

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/rule34vault.py, scripts/supportedsites.py, test/results/rule34vault.py
Based on rule34us extractor.
Fixes #5708.
=> [Rule34vault] Added support

gallery_dl/extractor/reddit.py, test/results/reddit.py
Spiritual follow-up to #4693 (time sure flies). Adds support for Reddit Mobile share links to a submission on a user-subreddit, e.g. https://www.reddit.com/u/Tailhook91/s/w4yAMbtOYm (expands to https://www.reddit.com/user/Tailhook91/comments/znfxbr/prove_it/?share_id=vUXyyXldTYSt2GDd5_WBL).
=> [reddit] support user profile share links

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/everia.py, test/results/everia.py
Supports posts, tags, categories, search results, and specific dates, months, or years
Resolves #4091
=> [everia.club] Add support

gallery_dl/extractor/philomena.py
The system filter mislabeled "Everything" hides 4 tags https://ponybooru.org/filters/2
There are [many public filters that don't hide anything](https://ponybooru.org/filters?fq=spoilered_count%3A0%2C+hidden_count%3A0), I just picked [the oldest one](https://ponybooru.org/filters/3).
=> [philomena] switch default ponybooru filter to get everything by default

gallery_dl/extractor/subscribestar.py
- We change the text.extr 3rd argument to match current structure ('class="post-edit_form"')
- We add support for uploads-audios based on a similar structure as the attachment type:
- id = data-upload-id
- name = audio_preview-title
- url = src
- type = audio
Fix #6721
=> [subscribestar] Fix attachment download and add support for audio type

gallery_dl/extractor/boosty.py
This PR addresses the issue mentioned in [gallery-dl#2387](https://github.com/mikf/gallery-dl/issues/2387#issuecomment-2564671646). Contrary to my comment the issue wasn’t with the use of cdn.boosty.to it turned out to be a missing data type handler.
=> [boosty] Added post attachment download

gallery_dl/extractor/subscribestar.py
The structure of content is like this:
```
<div class="post-content" data-role="post_content-text">
<div class="trix-content">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<body>
<div>
Unspeakable thing are written here<br />
<br />
haiiiiiiiiiiiiiiii hi hi hiii its meee back againnn, plspls leave a comment if uuuu liked it mwah
&lt;3
</div>
</body>
</html>
</div>
</div>
<div class="post-uploads
```
Currently we extract content with:
```
(extr('<div class="post-content', '<div class="post-uploads').partition(">")[2])
```
I propose we just take the body parts:
```
extr('<body>', '</body>')
```
which only happen when surrounding actual content.
It is then easier to use it in the filename content with the `!H` formatter: …
=> [subscribestar] Better extraction of content

gallery_dl/extractor/kemonoparty.py, test/results/kemonoparty.py
Hello,
I've added support for getting a creator that is filtered by a tag. The endpoint seems to be a legacy one as there is not an alternative.
I've also added some changes to support the /posts endpoint to work. It was failing if the config['metadata'] had been set due to it reaching out for a blank user/service id.
Fixed the pagination prematurely exiting also for those endpoints as they require a key for their results and the check was for the raw object.
=> Kemono Party - Support /posts endpoint and Creator Tag Calls

gallery_dl/extractor/lofter.py
1. Add 'NotFoundError' when the lofter blog returns a 404
2. Stop extractor if the blog is empty, because this returns {offset: -1} in the data which previously infinity-looped the extractor.
3. Prevents errors when the blog is locked, the posts in self.posts() are None
=> Add error messages in lofter extractor

gallery_dl/extractor/vsco.py, test/results/vsco.py
The JSON returned by VSCO assigns `undefined` to `["insights"]["prevPageToken"]` which is not a valid JSON value. We don't need this token anyway so we can safely remove it from the JSON before we parse it.
I've also updated a couple of the VSCO tests because they didn't pass on my local machine.
Closes: #6887
=> [VSCO] prevPageToken Bugfix

docs/supportedsites.md, gallery_dl/extractor/boosty.py, scripts/supportedsites.py, test/results/boosty.py
Adds `BoostyDirectMessageExtractor` as a new feature to fetch and process Boosty direct messages, including attachments. Updates `BoostyAPI` with `dialog`, `dialog_messages`, and `_pagination_dialog` methods for direct message retrieval. Verified that all file types can be successfully downloaded to the best of my capacity.
There is possibly a way to always fetch the DMs, but the `_dispatch_extractors` function is a bit too complex for me at the moment. Let me know if adjustments are needed or if this is out of scope.
=> [boosty] added new direct message extractor

gallery_dl/extractor/bunkr.py
This fixes #7058 
Currently bunkr returns an encrypted URL that can be locally decrypted by a local obfuscated javascript function. 
I have cracked the encryption / logic behind the obfuscated javascript and implemented it to obtain the URL
Tested on bunkr album links and it works
=> [bunkr] Bypassed URL encrpytion

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/deviantart.py, test/results/deviantart.py
Bumping the header version from `20200519` -> `20210526` which brings support for sub-folders in Gallery and Collections (allegedly). The Collections API doesn't *actually* expose sub-folders nor can I find an example of a collection folder.
> May 26th 2021
> Added new version 20210526
[/gallery/folders](https://www.deviantart.com/developers/http/v1/20240701/gallery_folders/f6104e0d969bbbdcf2154e4b221aa3a6) - Galleries now can display sub-folders
[/collections/folders](https://www.deviantart.com/developers/http/v1/20240701/collections_folders/35030a41b12db6c4edf6bf9b163e4327) - Collections now can display sub-folders
This will first iterate the `sub-folders` then proceed to do the main folder requested. I chose this path as it is not uncommon to have people put things in ***both*** the …
=> [DeviantArt] Support for Subfolders

gallery_dl/extractor/deviantart.py, test/results/deviantart.py
Adding support for multi image galleries. Currently there is no oAuth endpoint that returns this information - however the `deviationExtended` info that is found on the initial page load does have this information.
This will capture the information from the `additionalMedia` key on the `deviationExtended` metadata. I've added a few pieces of metadata to deviations:
1. `img_count` - number of images in total for the deviation page
2. `num` - What position the image is on the page
The default filename will use the `deviation_id` for the first image and the `fileId` for the subsequent images to make sure they are unique. This is done by updating the `index` value for the deviation.
Example gallery that can be used for testing (SFW)
> [October …
=> [DeviantArt] - Multi Image Gallery

gallery_dl/extractor/tiktok.py, test/results/tiktok.py
If you make 1000s+ of requests in a short duration of time, TikTok will refuse to publish rehydration data with a video page. This can happen quite frequently even when downloading just a few large user profiles. This PR attempts to address this by adding a retry and timeout mechanism to `_extract_rehydration_data()`.
Some other observations I've made:
- If a single link raises an exception when downloading a user page, I am of the opinion that it shouldn't cause the rest of the profile download to fail. But unsure how best to implement this.
- It would be nice to have some generic feature that prints all failed links at the end of processing, is there a feature that already supports this (not just reporting that a user profile failed to download fully, but reporting which links within …
=> [tiktok] Add retry mechanism to rehydration data extraction

gallery_dl/extractor/discord.py
Fixes #7341
The inconsistency stems from the fact that server channels are given in order of creation, which doesn't ensure that parents (categories) are parsed before their containing channels. I sorted the channels so that categories always get parsed first.
I've also handled an exception that occurred when trying to extract a channel with 0 messages.
=> [discord] fix "parent" keyword inconsistency (#7341)

docs/supportedsites.md, gallery_dl/extractor/twitter.py, test/results/twitter.py
Needed a follower extractor in addition to the existing following extractor.  Modeled after what you guys already have, follower extractor now enabled.  Hope this helps!
=> Twitter follower extractor

gallery_dl/extractor/instagram.py, test/results/instagram.py
As of december 2024, when copying the URL of a post from the Instagram Android app (I assume it's the same on other platforms) the real URL and tracking information are wrapped into a redirect formatted like: `https://www.instagram.com/share/reel/BARSSL4rTu`
The real post shortcode is not the same. Making a GET on this URL with proper Sec-Fetch headers, Instagram gives a code 302 response, with the real URL in the Location headers.
This is my first contributions, I'm not sure about the PR rules, and I'm not a python dev. Let me know if I need to make any changes. The security headers were copied from the Facebook extractor. I removed the /guide test as that instagram feature no longer exist.
=> [Instagram] Handle instagram.com/share/ URLs generated by the mobile app

docs/configuration.rst, gallery_dl/extractor/weasyl.py
To fit with their bot ettiquette: https://projects.weasyl.com/bot-etiquette
They're happy for gallery-dl to access the site and all, but would like better transparency on it
=> [weasyl] Set gallery-dl user agent to match danbooru user agent format, for weasyl

gallery_dl/extractor/pixiv.py
The pixiv extractor has one cached function `user_detail`, which sends `/v1/user/detail` requests to the mobile API for user metadata. Calls to `user_detail` throughout the extractor code sometimes have an integer user_id and sometimes string. Since this argument is used as a key for caching this function, it would in some cases cause an extra request to be made, for example if the first call was cached with a string version of the user_id and the second used an integer. This commit adds a wrapper for the cached user_detail function that converts the user_id argument to an integer in all cases.
It's just a suggestion, so if another solution for the wrapper fits the codebase better or if it would be preferred that the user_id argument type is handled before calls to the function, then I …
=>  [pixiv] fix user details request not being cached, causing extra requests

gallery_dl/extractor/pixiv.py
Fixing the root cause of a recently closed issue https://github.com/mikf/gallery-dl/issues/7422. It seems that extraction of all novel embeds was broken after a recent site change with the `meta-preload-data` no longer being present in html (which also broke pixivutil). This PR switches the php request with html parsing for an AJAX call that contains the same information.
=> [pixiv] fix novel embeds with AJAX request

gallery_dl/extractor/mastodon.py, test/results/mastodon.py
This trivial MR adds support of "notice" URLs for Pleroma/Akkoma.
Example of link: see the second commit
I didn't find any specific guidelines for contributions, sorry if tihs one isn't following them!
=> [mastodon] Add support for Akkoma/Pleroma /notice/:status_id urls + Some unit tests

docs/configuration.rst, docs/gallery-dl.conf, docs/supportedsites.md, gallery_dl/extractor/pixeldrain.py, scripts/supportedsites.py, test/results/pixeldrain.py
Based on [Fornaxian/pixeldrain_web/.../`FilesystemAPI.ts@6a45a48`](https://github.com/Fornaxian/pixeldrain_web/blob/6a45a485e90192b9dff3a511525fe7eac6679f6e/svelte/src/filesystem/FilesystemAPI.ts)
Happy to make any changes.
=> [pixeldrain] add support for filesystem URLs

gallery_dl/extractor/pixiv.py, test/results/pixiv.py
Ugoira with `limit_sanity_level` will fail to download properly, for both `ugoira: original` and if just downloading the zip. For such works, it is necessary to use an AJAX request for both the illust metadata (`https://www.pixiv.net/ajax/illust/<illust_id>`), to get the general illust metadata that is missing from the mobile API `/v1/user/illusts` response, and the ugoira metadata (`https://www.pixiv.net/ajax/illust/<illust_id>/ugoira_meta`) that also includes the frames, zip url etc. 
An example of this happening is for some reason this (very mildly NSFW): https://www.pixiv.net/en/artworks/103841583. It results in just the first frame being downloaded, since it's listed as the "original" image in the AJAX illust metadata and the current sanity level handling will not treat it as an …
=> [pixiv] Implement sanity handling for ugoira works

gallery_dl/extractor/everia.py, test/results/everia.py
Fixes non-latin filenames.
E.g.,
https://everia.club/2021/03/12/雯妹不讲道理-dido-ダイドー-azur-lane-碧蓝航线/
https://everia.club/2021/08/08/saika-kawakita-河北彩花-flash-2021-08-17-フラッシュ-2021年8月17日号/
=> [everia.club] unescape URLs

docs/configuration.rst
Running this in e.g. a detached container already gives the proper output mode, but the docs don't reflect that.
(thanks for this project!)
=> [docs] Update auto output mode documentation to reflect implementation

gallery_dl/extractor/foolfuuka.py, test/results/archivedmoe.py
Unless the board is /b/ (in which case redirection works fine), remove the characters of the filename portion of the url until filename portion of the url is 13 characters long (epoch millis).
Fixes #7652
=> [Archived.moe] Fix redirection issue

gallery_dl/extractor/inkbunny.py
This pull request allows the Inkbunny extractor to fetch metadata for `pools[]`. Currently, the extractor produces the `pools` property but always sets it to an empty array. This is because the API requires passing `show_pools: yes` in order to retrieve pool information.
I've flip-flopped on making this a new extractor option, but I decided not to since I don't think it will bloat the metadata file that much relative to its current size. Please let me know if I should change that.
I didn't notice any contribution guidelines so I hope I didn't miss anything.
=> Enable pool metadata on Inkbunny extractor

gallery_dl/extractor/facebook.py
Fixes #7834 and is probably also what's behind the issue at #7725 
I can see no discernible error message on the webpages that have not yet fully loaded, so I assume this is an inconsistency on Facebook's end. This doesn't mean there can't be a better way to fix this, this is just the bare minimum.
=> [facebook] add retries to profile page request

snap/snapcraft.yaml
This fixes the following warning during the pull
phase:
```
CRAFT_ARCH_TRIPLET is deprecated, use CRAFT_ARCH_TRIPLET_BUILD_{ON|FOR}
```
=> [snap] fix deprecated CRAFT_ARCH_TRIPLET usage

gallery_dl/postprocessor/exec.py, test/test_postprocessor.py
The session variable in the exec postprocessor defaults to `None` which results in the following exception:
```
File "[REDACTED]/gallery-dl/gallery_dl/job.py", line 153, in run
self.dispatch(msg)
File "[REDACTED]/gallery-dl/gallery_dl/job.py", line 204, in dispatch
self.handle_url(url, kwdict)
File "[REDACTED]/gallery-dl/gallery_dl/job.py", line 387, in handle_url
callback(pathfmt)
File "[REDACTED]/gallery-dl/gallery_dl/postprocessor/exec.py", line 75, in exec_list
retcode = self._exec(args, False)
File "[REDACTED]/gallery-dl/gallery_dl/postprocessor/exec.py", line 113, in _exec
if retcode := self._popen(args, shell).wait():
File "[REDACTED]/gallery-dl/gallery_dl/postprocessor/exec.py", line 120, in _popen
return util.Popen(
File …
```
=> Use False as default instead of None to avoid TypeError

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/hentaifoundry.py
It makes sense to have an option in an html-based extractor to preserve significant html.
+ Implementation immitates the very similar feature of the furaffinity extractor.
+ This only affects descriptions of image posts; stories already return html.
+ Example post with anchor tags in description: <https://www.hentai-foundry.com/pictures/user/TDL/1163076/The-Movement---Shineseal-Oil>
=> [hentai-foundry] Html description option

gallery_dl/extractor/imagebam.py
Hello,
As of a few days ago, it seems the imagebam extractor is broken.
On any given URL, I'd get this output in verbose mode:
```
[gallery-dl][debug] Starting DownloadJob for 'https://www.imagebam.com/image/3e141447416527'
[imagebam][debug] Using ImagebamImageExtractor for 'https://www.imagebam.com/image/3e141447416527'
[urllib3.connectionpool][debug] https://www.imagebam.com:443 "GET /image/3e141447416527 HTTP/1.1" 200 None
[imagebam][error] An unexpected error occurred: TypeError - argument of type 'NoneType' is not iterable. Please run gallery-dl again with the --verbose flag, copy its output and report this issue on https://github.com/mikf/gallery-dl/issues .
[imagebam][debug]
File "/home/bvergnaud/.local/share/uv/tools/gallery-dl/lib/python3.12/site …
```
=> fix(imagebam): update cookies to bypass guard page

docs/supportedsites.md, gallery_dl/extractor/danbooru.py, scripts/supportedsites.py, test/results/aibooru.py, test/results/atfbooru.py, test/results/booruvar.py, test/results/danbooru.py
This pull request adds support for the /posts/random endpoint from Danbooru-like sites. This allows users to fetch a random post matching a specific set of tags with URLs such as
https://danbooru.donmai.us/posts/random?tags=your_tag.
Motivation:
The /posts/random endpoint provides a more direct and efficient way to get a random post without needing to use order:random in a tag search. This is a convenient feature for users who want to quickly grab a random
image with specific tags without extra steps.
=> Adds a new `DanbooruRandomExtractor` to support downloading random posts.

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/wikimedia.py, test/results/wikipedia.py
This only works if the number of revisions of a single image doesn't exceed 500, which I think should cover the vast majority of images on most wikis.
=> [wikimedia] add ability to download image revisions
