mikf/gallery-dl

gallery_dl/extractor/__init__.py, gallery_dl/extractor/slideshare.py
Add a new extractor for www.slideshare.net.
=> [slideshare] Add a new extractor for slideshare.net

gallery_dl/extractor/shopify.py
Glanced over the commits, randomly spotted some minor things.
=> [shopify] cosmetic changes in shopify.py

.gitignore
=> Ignore generated manpages and bash completion data

gallery_dl/extractor/instagram.py
Add support for IGTV profile (instagram.com/<username>/channel/)
and IGTV medias (instagram.com/tv/<short_id>).
=> [instagram] Add support for IGTV

README.rst
To be honest, I feel a bit unsure here about things like phrasing, tone, style etc.  
Very relevant 😄. Me thinks it sounds polite enough though.
Feel free to change anything, of course.
=> Add basic package version notice to README.rst

gallery_dl/extractor/__init__.py, gallery_dl/extractor/speakerdeck.py, scripts/supportedsites.py
The following PR add a new extractor for speakerdeck.com to extract all
slides from a presentation.
=> [speakerdeck] Add a new extractor for speakerdeck.com

gallery_dl/extractor/common.py, gallery_dl/option.py
=> Implement --write-pages option

gallery_dl/extractor/__init__.py, gallery_dl/extractor/imagechest.py, scripts/supportedsites.py
I would hold off adding additional metadata properties for this extractor since there doesn't seem to be a consistent way of grabbing stuff like view counts and descriptions right now.
I also would suggest a documentation page (or giant section of comments like youtube-dl) explaining what should be done when creating a new extractor. I essentially had to reverse engineer other extractors and common.py for example just to figure out where I was going wrong when making this.
=> [imagechest] Add new extractor for ImageChest

docs/supportedsites.rst, gallery_dl/extractor/__init__.py, gallery_dl/extractor/mangakakalot.py, scripts/supportedsites.py
I've added a new extractor for MangaKakalot. Please let me know if there are any issues, as I don't normally write Python.
=> Added extractor for MangaKakalot

gallery_dl/extractor/twitter.py
This pull request add support for nitter.net URLs.
Nitter is an alternative front-end to Twitter - free and open-source available
at: <https://github.com/zedeus/nitter>
nitter.net is the official public instance.
=> [twitter] add support for nitter.net URLs in pattern

docs/supportedsites.rst
Fixes https://github.com/mikf/gallery-dl/issues/889
=> mention optional auth access for furaffinity

README.rst
Found this feature super useful for tumblr blogs that use custom domains but it wasn't well documented so heres an example for the readme.
=> Document Extractor Prefixing

gallery_dl/extractor/__init__.py, gallery_dl/extractor/myhentaigallery.py, scripts/supportedsites.py
This pull request adds support for downloading of galleries from https://myhentaigallery.com.
=> Extractor for myhentaigallery.com

README.rst
As not everyone is willing to use complicated chocolatey.
=> Add some hints for scoop users

docs/configuration.rst, docs/supportedsites.rst, gallery_dl/extractor/weasyl.py, scripts/supportedsites.py
Fixes this [comment](https://github.com/mikf/gallery-dl/pull/977#issuecomment-706644335)
Required to download NSFW images.
=> [weasyl] api-key authentication

docs/supportedsites.rst, gallery_dl/extractor/imagehosts.py
Adds support for images hosted on https://vipr.im
I couldn't figure out how the tests work. If you give me a hint, I'll be glad to hand them in.
=> [vipr] add image extractor

docs/supportedsites.rst, gallery_dl/extractor/__init__.py, gallery_dl/extractor/cyberdrop.py
=> cyberdrop extractor

gallery_dl/extractor/__init__.py, gallery_dl/extractor/tumblrgallery.py, scripts/supportedsites.py
I am not sure how to write tests for this project please let me know if I need to change it.
=> support `tumblrgallery.xyz`

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/exhentai.py
partially revert https://github.com/mikf/gallery-dl/commit/e9ec91c811ac34620e9d4b0e12c0e9237336bf14
restoring exhentai limits config
keep new throttle detection
=> restore exhentai limits configuration

gallery_dl/extractor/nozomi.py
=> [nozomi] Extend default archive-fmt for Tag and Search Extractor

gallery_dl/extractor/mangafox.py
Adding "title" for chapters would be nice. I will look into the extractor for mangahere and see what I can copy from :) Otherwise I can download mangas with the current state.
=> Add MangaExtractor for mangafox

gallery_dl/extractor/hitomi.py
Hitomi image rule changed
This PR solves the problem that some works are not visible
ref: https://ltn.hitomi.la/common.js
=> fix(hitomi): fix image URLs

gallery_dl/extractor/__init__.py, gallery_dl/extractor/wikieat.py
The site is very similar to 8kun which is already supported, so this is a basic copypaste job from that site's extractor. The tests don't test anything properly since I don't know how to write them. Hopefully someone can help with that.
Closes #1607
=> Add Wikieat extractor

gallery_dl/extractor/__init__.py, gallery_dl/extractor/kohlchan.py
Lets you download media from threads on the imageboard Kohlchan
https://kohlchan.net/ (warning: NSFW)
=> Add Kohlchan extractor

gallery_dl/extractor/hentaicosplays.py
I can't download images if no Referer is in headers.
=> [hentaicosplays] add Referer to headers

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/gofile.py
Test folder: https://gofile.io/d/LEjH16
=> Add gofile.io extractor

gallery_dl/extractor/tumblr.py
This PR only fixes the second post mentioned in #1344
=> [tumblr] attempt to get higher-quality images

gallery_dl/extractor/fanbox.py
=> fanbox: download cover images in original size

docs/supportedsites.md, gallery_dl/extractor/2chen.py, gallery_dl/extractor/__init__.py, scripts/supportedsites.py
=> [2chen] Add 2chen.moe extractor

gallery_dl/extractor/hentai2read.py
closes #3088 
``` bash
$ py -m gallery_dl -s "https://hentai2read.com/popuni_kei_joshi_panic/2.5/"
[...]
```
=> [hentai2read] recognize '.' in chapter

docs/supportedsites.md, gallery_dl/extractor/lolisafe.py, scripts/supportedsites.py
=> [lolisafe] add support for xbunkr

gallery_dl/extractor/tumblr.py
Fixes #3095 
Update: Moved code to `_prepare_image`.
=> [tumblr] Fallback to `gifv` when possible (#3095)

gallery_dl/extractor/imagehosts.py
=> [imxto] extract additional metadata

gallery_dl/extractor/khinsider.py
closes #3215 
``` bash
$ py -m gallery_dl -s https://downloads.khinsider.com/game-soundtracks/album/dyson-sphere-program
...
```
=> [khinsider] fix song extraction

docs/supportedsites.md, gallery_dl/extractor/wallhaven.py
related to #3212 
uses the search endpoint to get wallpapers from a user
- updated tests (pattern)
- added `self.api` to base extractor
=> [wallhaven] add 'user' extractor

docs/configuration.rst, docs/gallery-dl.conf, gallery_dl/extractor/wallhaven.py, scripts/supportedsites.py
I think this is better than just updating the `pattern`
=> [wallhaven] update 'user' extractor

gallery_dl/extractor/itaku.py
=> [itaku] remove 'Extreme' rating

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/fapachi.py, scripts/supportedsites.py
=> [fapachi] add 'post' and 'user' extractors

docs/supportedsites.md, gallery_dl/extractor/imagehosts.py
=> [pixhost] add 'gallery' support

gallery_dl/extractor/imgur.py
Imgur has been redirecting me to imgur.io on my phone for a few months now.
=> [imgur] add support for imgur.io URLs

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/fapello.py, scripts/supportedsites.py
=> [fapello] add 'post', 'user' and 'path' extractors

docs/supportedsites.md, gallery_dl/extractor/lynxchan.py
=> [lynxchan/bbw-chan] add 'thread' and 'board' extractors

README.rst
Hi! [Just noticed these instructions seemed to be missing.](https://formulae.brew.sh/formula/gallery-dl)
Have a good one!
=> Add Homebrew instructions to installation list

docs/configuration.rst, gallery_dl/extractor/twitter.py
Accidentally deleted the branch from the last pull request.
=> [twitter] fix crash when using `expand` and `syndication`

docs/configuration.rst
Partially resolves https://github.com/mikf/gallery-dl/issues/2712.
=> [twitter] document #1396 and #2712

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/nudecollect.py
=> [nudecollect] add 'image' and 'album' extractors

gallery_dl/extractor/hotleak.py
Related to #3516
Reverse engineered obfuscated JS function and reimplemented in python.
=> [Hotleak] Fix video URLs

docs/supportedsites.md, gallery_dl/extractor/shopify.py, scripts/supportedsites.py
=> [shopify] support ohpolly.com

gallery_dl/extractor/redgifs.py
=> [redgifs] support v3 URLs

gallery_dl/extractor/redgifs.py
=> [redgifs] add 'collection' extractors

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/misskey.py, scripts/supportedsites.py
closes #3714 
~will add `text-notes`, `renotes`, `replies` options later, please tell me if more extractors are needed.~
=> [misskey] add misskey extractors

gallery_dl/extractor/shopify.py
=> [shopify] fix 'collection' extractor

gallery_dl/extractor/blogger.py
=> [blogger] update 'sub' regex to get the highest resolution url

gallery_dl/extractor/mangadex.py
Adding info about series status and tags.
=> add status and tags info to mangadex extractor

gallery_dl/extractor/twitter.py
=> [twitter] extract TwitPic URLs in text (#3792)

gallery_dl/extractor/misskey.py
This will saves images from favorites. Saving favorites requires access token with "View your list of favorites" permission.
=> [misskey] add my favorites extractor

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/mangaread.py, scripts/supportedsites.py
=> [mangaread] Add Mangaread extractor

gallery_dl/extractor/__init__.py, gallery_dl/extractor/lensdump.py
Add support for lensdump.com.
Example links:
- https://lensdump.com/a/jl24M
- https://lensdump.com/i/0VlLT2
- https://lensdump.com/love_nikki
- https://lensdump.com/love_nikki/albums
#2078
=> [lensdump] add lensdump.com extractor

gallery_dl/extractor/imagehosts.py
#3115 
- add gallery support
- update image extractor to download original image instead of main image
=> [postimage] add gallery support, update image extractor

gallery_dl/extractor/twitter.py
fixes following extractor only extracting some users, in my case 
before = only gets 49 users
after = gets entire 517 users
=> [twitter] Fix following extractor not getting the whole following list

gallery_dl/extractor/wikifeet.py
=> [wikifeet] fix 'tag' extraction

gallery_dl/extractor/gelbooru_v01.py
=> [gelbooru_v01] fix 'source' (#4302)

docs/supportedsites.md, gallery_dl/extractor/redgifs.py
=> [redgifs] add 'niches' extractor

gallery_dl/extractor/zerochan.py
=> [zerochan] fix 'tags' extraction

gallery_dl/downloader/http.py
=> [downloader:http] close connection when file already exists

gallery_dl/extractor/redgifs.py, test/results/redgifs.py
=> [redgifs] fix 'niches' extraction

gallery_dl/extractor/patreon.py
PR for issue https://github.com/mikf/gallery-dl/issues/4736. Feel free to change, accept or decline it.
=> Try to parse newer HTTP response from Patreon

gallery_dl/extractor/twitter.py
After fxtwitter, vxtwitter etc., the newest embed-fixing-twitter-redirect site I've seen spreading is fixupx.com
=> [twitter] recognize fixupx.com URLs

gallery_dl/extractor/erome.py
Add "count" as a directory keyword for erome.
=> [erome] add "count" for albums

gallery_dl/extractor/fapello.py, test/results/fapello.py
=> [fapello] support '.su' TLD

gallery_dl/extractor/nitter.py, test/results/nitternet.py
=> [nitter] fix video extraction

docs/configuration.rst, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/postmill.py, scripts/supportedsites.py, test/results/raddle.py
For `PostmillPostExtractor`, I've only added what I need (out of laziness), though I am willing to add more keywords on request.
Fixes #4917
=> [postmill] add support

gallery_dl/extractor/pixiv.py
Update User-Agent for pixiv API
=> [pixiv] Cannot retrive R-18/R-18G Images

gallery_dl/path.py
=> Fix filename formatting silently failing under certain circumstances

gallery_dl/extractor/bunkr.py
New TLDs for bunkr after sampling a few large albums:
* .si
* .ac
* .black
* .cat
* .media
* .red
* .site
* .ws
Fixes: #5130
=> [bunkr] add new bunkr domains (#5130)

gallery_dl/extractor/imagefap.py, test/results/imagefap.py
Tested with 
Previously working
```
gallery-dl --cookies-from firefox https://www.imagefap.com/organizer/609096 
```
and 
previously NOT working but now fixed
```
gallery-dl --cookies-from firefox https://www.imagefap.com/organizer/613950/Grace-Stout      
```
=> [Imagefap] Fix imagefap extractor

gallery_dl/extractor/furaffinity.py, gallery_dl/extractor/twitter.py, test/results/furaffinity.py, test/results/twitter.py
I run into those quite often on Discord so its a good idea to support them.
=> [twitter] [furaffinity] match fixvx.com and fxfuraffinity/fxraffinity.net urls

gallery_dl/extractor/furaffinity.py, test/results/furaffinity.py
=> [furaffinity] Match xfuraffinity.com

gallery_dl/extractor/poipiku.py
Fixes #5590.
The old extr only works if the UI is English.
=> [poipoku] avoid language-specific extr

gallery_dl/extractor/hentainexus.py
Nice work doing the initial deobsfucation. Updated it cause they're tweaking things but who knows how long til it breaks again.
=> update nexus key

gallery_dl/extractor/redgifs.py
Update redgifs.py to include 0-9 regex, fixes #5898
First pull request to this repo, willing to accept any criticism/input/etc.
Thanks!
=> Update redgifs.py to include 0-9 regex, fixes #5898

gallery_dl/extractor/bunkr.py
Domains added:
- https://bunkr.ci
- https://bunkrrr.org
=> [bunkr] Add support for more domains

gallery_dl/extractor/batoto.py
=> [bato] fix chapter info regex

gallery_dl/extractor/cohost.py
turns out it's almost the same as tags, so I was able to get it working pretty easily
=> [cohost] Support for downloading likes

gallery_dl/extractor/bluesky.py, test/results/bluesky.py
Those got a lot more common lately due to many artists moving.
=> [bluesky] Match common bluesky embed fixes

gallery_dl/extractor/bluesky.py, test/results/bluesky.py
=> [bluesky] Match fxbsky.app and vxbsky.app urls

docs/supportedsites.md, gallery_dl/extractor/tumblr.py, test/results/tumblr.py
Adds support for extracting posts from search urls in Tumblr.
Time parameter 't' is also respected when present in the url.
=> [tumblr] add tumblr search support

gallery_dl/extractor/koharu.py, test/results/koharu.py
=> [koharu] updat root and root_api change

gallery_dl/extractor/imagechest.py
Hi there,
the ImageChest extractor is not working anymore (since there is a new page layout).
This PR will fix it.
Thanks!
=> fix imagechest extractor

docs/gallery-dl.conf, scripts/docs_compare.py
An initial attempt at updating the default config file, which was neglected for quite some time.
I'd like to collect some feedback regarding possible improvements, formatting, errors, and so on.
I'd also like to add a script that checks this file's settings with the ones from `docs/configuration.rst` and default extractor `request_interval` values, maybe more.
Another idea: extend `--config-create` and allow passing an argument specifying which type of config to "create": `empty`/`blank`, `basic` (what is currently used) , or `default` (this file).
=> [docs] update gallery-dl.conf

gallery_dl/extractor/__init__.py, gallery_dl/extractor/lofter.py
Chinese tumblr.
Related: #650, #2294, #4095, #4728, #5656
=> [lofter]: add initial support

gallery_dl/extractor/itaku.py, test/results/itaku.py
I haven't actually run the tests in `test/results/itaku.py` because I don't know how to but I have run it manually and it seems to work fine.
=> [itaku] add 'search' extractor

docs/supportedsites.md, gallery_dl/extractor/imagehosts.py, test/results/turboimagehost.py
Single image support already existed, now galleries also work
=> [TurboImageHost] added support for galleries

docs/supportedsites.md, gallery_dl/extractor/foolfuuka.py, scripts/supportedsites.py, test/results/b4k.py
=> [b4k] update domain to arch.b4k.dev

docs/supportedsites.md, gallery_dl/extractor/furaffinity.py, test/results/furaffinity.py
Which just extracts a single folder, rather than an entire gallery, of an FA user.
As requested in #1817
=> [furaffinity] Adding a FuraffinityFolderExtractor

docs/supportedsites.md, gallery_dl/extractor/itaku.py, test/results/itaku.py
Just adding a new extractor which handles itaku stars, so, downloading someone's favourites on the site. API is pretty similar to gallery, so it's not much change needed to add stars
=> [itaku] Add a new extractor for Itaku stars

gallery_dl/cookies.py
Fixes https://github.com/mikf/gallery-dl/issues/7233
=> [cookies] add support for Zen Browser

gallery_dl/extractor/sexcom.py, test/results/sexcom.py
https://www.sex.com/en/pics/1459016
=> Add support for /pics/ URLs on sex.com

gallery_dl/extractor/discord.py
=> [discord] support forwarded messages + handle missing threads

docs/configuration.rst, docs/gallery-dl.conf, docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/chzzk.py, test/results/chzzk.py
=> [chzzk] add 'comment' and 'community' extractors

snap/snapcraft.yaml
As per https://github.com/mikf/gallery-dl/pull/7841#pullrequestreview-3030959915.
=> [snap] switch to yt-dlp

docs/supportedsites.md, gallery_dl/extractor/kemono.py, scripts/supportedsites.py, test/results/coomer.py, test/results/kemono.py
Kemono.party and Coomer.party both recently changed their site domains, i have updated the extractor to use those new domains.
=> [kemonoparty] update extractor to use new domains

docs/supportedsites.md, gallery_dl/extractor/__init__.py, gallery_dl/extractor/xasiat.py, test/results/xasiat.py
Supports albums, tags, categories, and models.
Fixes #5929
Fixes #4161
=> Add xasiat.com extractor

gallery_dl/extractor/chevereto.py
Videos are now correctly handled.
=> Chevereto Albums were not downloading videos

gallery_dl/cookies.py
additionally break out webkit support for future webkit based browsers/tools
=> [cookies] add support for Orion
